---
- name: Pull docker image of mlops_proj
  hosts: localhost
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: "{{item}}"
        dest: /tmp/
      with_items:
        - docker-compose.yml
        - sdm_logfile.log
        - filebeat.yml
        - logstash.conf
        - db
     
